---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  sourceNamespaces:
  - '*'
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  image: registry.redhat.io/openshift-gitops-1/argocd-rhel8
  version: sha256:706d5c99715eece77616135da2fbf90863b7aef17fd64ab03bf7dd20877490ec
  controller:
    enabled: true
    processors: {}
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    env:
      - name: ARGOCD_APPLICATION_NAMESPACES
        valueFrom:
          configMapKeyRef:
            name: argocd-cmd-params-cm
            key: application.namespaces
            optional: true
  redis:
    image: registry.redhat.io/rhel8/redis-6
    version: sha256:a848cc4edb4405846c673187dd68ce66c328dd1ad42f193f5737288c7971399d
    enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    image: registry.redhat.io/openshift-gitops-1/argocd-rhel8
    version: sha256:706d5c99715eece77616135da2fbf90863b7aef17fd64ab03bf7dd20877490ec
    enabled: true
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  rbac:
    defaultPolicy: "role:admin"
    policy: |
      g, cluster-admins, role:admin
  applicationSet:
    enabled: false
  grafana:
    enabled: false
  ha:
    enabled: false
  server:
    enabled: false
  monitoring:
    enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
