apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
  name: example
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: example
  type: LoadBalancer
