resources:
- ../base

patches:
- target:
    kind: KlusterletAddonConfig
  patch: |
    - op: replace
      path: /metadata/name
      value: "namctigtd27d"
    - op: replace
      path: /metadata/namespace
      value: "namctigtd27d"
    - op: replace
      path: /spec/clusterName
      value: "namctigtd27d"
    - op: replace
      path: /spec/clusterNamespace
      value: "namctigtd27d"
- target:
    kind: ManagedCluster
  patch: |
    - op: replace
      path: /metadata/name
      value: "namctigtd27d"
    - op: replace
      path: /metadata/namespace
      value: "namctigtd27d"
    - op: add
      path: /metadata/labels
      value:
        datacenter: gtdc
        environment: dev
        monitoring_config_enabled: enabled
        region: nam
        sector: cti
        vault-csi-provider-enabled: true

- target:
    kind: Namespace
  patch: |
    - op: replace
      path: /metadata/name
      value: "namctigtd27d"
