apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: playback-ns
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: redis
    tier: backend
    role: slave
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    tier: backend
    role: slave
