apiVersion: v1
data:
  database: mongodb
kind: ConfigMap
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
    apps.open-cluster-management.io/channel: ch-obj/backend-test
  labels:
    apps.open-cluster-management.io/channel: object-minio
    apps.open-cluster-management.io/channel-type: ObjectBucket
  name: cfg-from-ch-qa4

