apiVersion: v1
data:
  database: mongodb
kind: ConfigMap
metadata:
  labels:
    apps.open-cluster-management.io/channel: object-minio
    apps.open-cluster-management.io/channel-type: ObjectBucket
  name: cfg-from-ch-qa

